function [objectiveValue, result] = evaluate_two_view_design(azimuthDeg, elevationDeg, baselineVal, cfg)
%EVALUATE_TWO_VIEW_DESIGN Evaluate one opposite-side two-view tanker design.
%
% Inputs:
%   azimuthDeg   -> first-view azimuth in degrees
%   elevationDeg -> common elevation in degrees
%   baselineVal  -> stereo baseline in meters
%   cfg          -> config struct
%
% Outputs:
%   objectiveValue -> scalar loss
%   result         -> struct with key metrics for logging

    % ------------------------------------------------------------
    % Round / clamp design variables
    % ------------------------------------------------------------
    azimuthDeg   = round(double(azimuthDeg));
    elevationDeg = round(double(elevationDeg));
    baselineVal  = round(double(baselineVal), 3);

    azimuthDeg   = min(max(azimuthDeg,   cfg.azimuth_bounds(1)),   cfg.azimuth_bounds(2));
    elevationDeg = min(max(elevationDeg, cfg.elevation_bounds(1)), cfg.elevation_bounds(2));
    baselineVal  = min(max(baselineVal,  cfg.baseline_bounds(1)),  cfg.baseline_bounds(2));

    azimuthOppDeg = mod(azimuthDeg + 180, 360);

    % ------------------------------------------------------------
    % VIEW A
    % ------------------------------------------------------------
    [renderDataA, rigA, sceneInfoA] = render_jason_ship_stereo( ... %#ok<NASGU,ASGLU>
        'ShipScript', cfg.ship_script, ...
        'AzimuthDeg', azimuthDeg, ...
        'ElevationDeg', elevationDeg, ...
        'Range', cfg.range, ...
        'Baseline', baselineVal, ...
        'ImageSize', cfg.image_size, ...
        'HFOVDeg', cfg.hfov_deg, ...
        'MakeFigure', false, ...
        'Verbose', false, ...
        'SaveImages', false);

    reconA = reconstruct_pointcloud(renderDataA, rigA, ...
        'DisparityRange', cfg.disparity_range, ...
        'MakeFigure', false, ...
        'Verbose', false, ...
        'SavePointCloud', false, ...
        'MaxDepth', cfg.max_depth, ...
        'UseAdaptiveHistEq', cfg.use_adapthisteq, ...
        'MinValidDisparity', cfg.min_valid_disparity, ...
        'BackgroundThreshold', cfg.background_threshold);

    % ------------------------------------------------------------
    % VIEW B
    % ------------------------------------------------------------
    [renderDataB, rigB, sceneInfoB] = render_jason_ship_stereo( ... %#ok<NASGU,ASGLU>
        'ShipScript', cfg.ship_script, ...
        'AzimuthDeg', azimuthOppDeg, ...
        'ElevationDeg', elevationDeg, ...
        'Range', cfg.range, ...
        'Baseline', baselineVal, ...
        'ImageSize', cfg.image_size, ...
        'HFOVDeg', cfg.hfov_deg, ...
        'MakeFigure', false, ...
        'Verbose', false, ...
        'SaveImages', false);

    reconB = reconstruct_pointcloud(renderDataB, rigB, ...
        'DisparityRange', cfg.disparity_range, ...
        'MakeFigure', false, ...
        'Verbose', false, ...
        'SavePointCloud', false, ...
        'MaxDepth', cfg.max_depth, ...
        'UseAdaptiveHistEq', cfg.use_adapthisteq, ...
        'MinValidDisparity', cfg.min_valid_disparity, ...
        'BackgroundThreshold', cfg.background_threshold);

    % ------------------------------------------------------------
    % MERGE
    % ------------------------------------------------------------
    reconMerged = merge_reconstructed_clouds(reconA, reconB, ...
        'VoxelSize', cfg.merge_voxel_size, ...
        'MakeFigure', false, ...
        'Verbose', false);

    % ------------------------------------------------------------
    % GT metrics
    % ------------------------------------------------------------
    metricsMerged = compute_gt_metrics_jason_ship(reconMerged, ...
        'CropX', cfg.crop_x, ...
        'CropY', cfg.crop_y, ...
        'CropZ', cfg.crop_z, ...
        'GTMeshSpacing', cfg.gt_mesh_spacing, ...
        'MaxEvalPoints', cfg.max_eval_points, ...
        'ChunkSizeNN', cfg.chunk_size_nn, ...
        'ChunkSizeMesh', cfg.chunk_size_mesh, ...
        'TriangleCandidates', cfg.triangle_candidates, ...
        'MakeFigure', false, ...
        'Verbose', false);

    % ------------------------------------------------------------
    % Losses / scores
    % ------------------------------------------------------------
    accuracyLoss = ...
        0.75 * metricsMerged.mesh_surface_one_sided_rmse + ...
        0.20 * metricsMerged.centroid_one_sided_rmse - ...
        0.05 * metricsMerged.covered_gt_area_fraction_005;

    coverageScore = ...
        0.20 * metricsMerged.covered_gt_area_fraction_005 + ...
        0.50 * metricsMerged.covered_gt_area_fraction_010 + ...
        0.30 * metricsMerged.covered_gt_area_fraction_020;

    coverageLoss = 1.0 - coverageScore;

    switch lower(cfg.objective_mode)
        case 'accuracy'
            objectiveValue = accuracyLoss;
        case 'coverage'
            objectiveValue = coverageLoss;
        case 'balanced'
            objectiveValue = 0.60 * accuracyLoss + 0.40 * coverageLoss;
        otherwise
            objectiveValue = accuracyLoss;
    end

    % ------------------------------------------------------------
    % Pack result struct
    % ------------------------------------------------------------
    result = struct();

    result.azimuth_deg = azimuthDeg;
    result.azimuth_opp_deg = azimuthOppDeg;
    result.elevation_deg = elevationDeg;
    result.baseline = baselineVal;

    result.objective_mode = string(cfg.objective_mode);
    result.objective_value = objectiveValue;

    result.accuracy_loss = accuracyLoss;
    result.coverage_loss = coverageLoss;
    result.coverage_score = coverageScore;

    result.mesh_surface_one_sided_rmse = metricsMerged.mesh_surface_one_sided_rmse;
    result.centroid_one_sided_rmse = metricsMerged.centroid_one_sided_rmse;
    result.centroid_symmetric_rmse = metricsMerged.centroid_symmetric_rmse;
    result.proxy_symmetric_rmse = metricsMerged.proxy_symmetric_rmse;

    result.covered_gt_area_fraction_005 = metricsMerged.covered_gt_area_fraction_005;
    result.covered_gt_area_fraction_010 = metricsMerged.covered_gt_area_fraction_010;
    result.covered_gt_area_fraction_020 = metricsMerged.covered_gt_area_fraction_020;

    result.covered_gt_triangle_fraction_005 = metricsMerged.covered_gt_triangle_fraction_005;
    result.covered_gt_triangle_fraction_010 = metricsMerged.covered_gt_triangle_fraction_010;
    result.covered_gt_triangle_fraction_020 = metricsMerged.covered_gt_triangle_fraction_020;

    result.raw_point_count = metricsMerged.raw_point_count;
    result.cropped_point_count = metricsMerged.cropped_point_count;
    result.keep_fraction = metricsMerged.keep_fraction;
    result.cropped_points_per_covered_gt_area_010 = metricsMerged.cropped_points_per_covered_gt_area_010;

    if isfield(reconMerged, 'final_merged_point_count')
        result.final_merged_point_count = reconMerged.final_merged_point_count;
    else
        result.final_merged_point_count = NaN;
    end

    if isfield(metricsMerged, 'total_gt_area')
        result.total_gt_area = metricsMerged.total_gt_area;
    else
        result.total_gt_area = NaN;
    end
end