clc; clear; close all;
% Exploratory 4-view fusion capstone study.
% Headless, summary-first, no popup figures.

studyTag = char(string(datetime('now', 'Format', 'yyyyMMdd_HHmmss')));
thisScriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(thisScriptDir));

studyRoot   = fullfile(projectRoot, 'outputs', ['four_view_capstone_' studyTag]);
metricsDir  = fullfile(studyRoot, 'metrics');
if ~exist(studyRoot, 'dir'), mkdir(studyRoot); end
if ~exist(metricsDir, 'dir'), mkdir(metricsDir); end

%% ------------------------------------------------------------
% FIXED SETTINGS
% -------------------------------------------------------------
elevationDeg = 10;
rangeVal     = 18;
baselineVal  = 0.20;
imageSizeVal = [720 1280];
hfovDegVal   = 16;

viewAzList   = [45 135 225 315];
mergeVoxelSizeVal = 0.01;

% Same reconstruction settings as your sweep
disparityRangeVal      = [16 64];
maxDepthVal            = 30;
minValidDispVal        = 16;
backgroundThresholdVal = 245;

cropXVal = [-0.2 8.8];
cropYVal = [-1.4 1.4];
cropZVal = [0.0 2.8];

gtMeshSpacingVal      = 0.10;
maxEvalPointsVal      = 30000;
chunkSizeNNVal        = 300;
chunkSizeMeshVal      = 120;
triangleCandidatesVal = 12;

%% ------------------------------------------------------------
% OPTIONAL REFERENCE CASE
% -------------------------------------------------------------
% Accuracy-first champion from previous study
referencePair = [25 205];
referenceCaseLabel = sprintf('reference_pair_az%03d_%03d_el%02d_b%03d', ...
    referencePair(1), referencePair(2), round(elevationDeg), round(1000*baselineVal));

%% ------------------------------------------------------------
% SUMMARY TABLE
% -------------------------------------------------------------
results = table();

fprintf('\n============================================================\n');
fprintf('FOUR-VIEW CAPSTONE STUDY\n');
fprintf('Views: [%s]\n', num2str(viewAzList));
fprintf('Elevation: %.1f deg | Baseline: %.3f | Range: %.1f | HFOV: %.1f\n', ...
    elevationDeg, baselineVal, rangeVal, hfovDegVal);
fprintf('Output folder:\n%s\n', studyRoot);
fprintf('============================================================\n\n');

%% ------------------------------------------------------------
% REFERENCE SINGLE-PAIR CHAMPION
% -------------------------------------------------------------
try
    refOutDir = fullfile(studyRoot, referenceCaseLabel);
    if ~exist(refOutDir, 'dir'), mkdir(refOutDir); end

    refMetrics = run_one_pair_case( ...
        referencePair(1), referencePair(2), elevationDeg, baselineVal, ...
        rangeVal, hfovDegVal, imageSizeVal, refOutDir);

    results = [results; make_row( ...
        referenceCaseLabel, ...
        "reference_single_pair", ...
        sprintf('%d,%d', referencePair(1), referencePair(2)), ...
        2, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
        refMetrics.mesh_rmse_m, ...
        refMetrics.sym_centroid_rmse_m, ...
        refMetrics.gt_area_005, ...
        refMetrics.gt_area_010, ...
        refMetrics.gt_area_020, ...
        refMetrics.cropped_pts, ...
        string(refMetrics.status), ...
        string(refMetrics.notes), ...
        string(refOutDir))];
catch ME
    warning('Reference pair failed: %s', ME.message);
    results = [results; make_row( ...
        referenceCaseLabel, ...
        "reference_single_pair", ...
        sprintf('%d,%d', referencePair(1), referencePair(2)), ...
        2, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
        NaN, NaN, NaN, NaN, NaN, NaN, "failed", string(ME.message), string(refOutDir))];
end

%% ------------------------------------------------------------
% RUN FOUR SINGLE VIEW RECONSTRUCTIONS
% -------------------------------------------------------------
reconCell    = cell(numel(viewAzList),1);
metricsCell  = cell(numel(viewAzList),1);
statsCell    = cell(numel(viewAzList),1);

for i = 1:numel(viewAzList)
    az = viewAzList(i);
    caseLabel = sprintf('single_view_az%03d_el%02d_b%03d', ...
        round(az), round(elevationDeg), round(1000*baselineVal));
    caseOutDir = fullfile(studyRoot, caseLabel);
    if ~exist(caseOutDir, 'dir'), mkdir(caseOutDir); end

    fprintf('Running single-view rig center at azimuth %.1f...\n', az);

    [reconCell{i}, statsCell{i}, metricsCell{i}] = run_single_view_reconstruction( ...
        az, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
        disparityRangeVal, maxDepthVal, minValidDispVal, backgroundThresholdVal, ...
        cropXVal, cropYVal, cropZVal, ...
        gtMeshSpacingVal, maxEvalPointsVal, chunkSizeNNVal, chunkSizeMeshVal, triangleCandidatesVal);

    save(fullfile(caseOutDir, sprintf('%s_metrics.mat', caseLabel)), ...
        'az', 'elevationDeg', 'baselineVal', 'rangeVal', 'hfovDegVal', 'imageSizeVal');

    write_case_txt(fullfile(caseOutDir, sprintf('%s_summary.txt', caseLabel)), ...
        caseLabel, az, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, metricsCell{i});

    results = [results; make_row( ...
        caseLabel, ...
        "single_view", ...
        sprintf('%d', az), ...
        1, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
        metricsCell{i}.mesh_surface_one_sided_rmse, ...
        metricsCell{i}.centroid_symmetric_rmse, ...
        metricsCell{i}.covered_gt_area_fraction_005, ...
        metricsCell{i}.covered_gt_area_fraction_010, ...
        metricsCell{i}.covered_gt_area_fraction_020, ...
        metricsCell{i}.cropped_point_count, ...
        "ok", "", string(caseOutDir))];
end

%% ------------------------------------------------------------
% MERGE OPPOSITE PAIRS
% -------------------------------------------------------------
% Pair A: 45 + 225
pairA_label = sprintf('pair_045_225_el%02d_b%03d', round(elevationDeg), round(1000*baselineVal));
pairA_outDir = fullfile(studyRoot, pairA_label); if ~exist(pairA_outDir, 'dir'), mkdir(pairA_outDir); end
reconPairA = merge_reconstructed_clouds(reconCell{1}, reconCell{3}, ...
    'VoxelSize', mergeVoxelSizeVal, 'MakeFigure', false, 'Verbose', false);
statsPairA = analyze_pointcloud(reconPairA, ...
    'CropX', cropXVal, 'CropY', cropYVal, 'CropZ', cropZVal, ...
    'MakeFigure', false, 'Verbose', false);
metricsPairA = compute_gt_metrics_jason_ship(reconPairA, ...
    'CropX', cropXVal, 'CropY', cropYVal, 'CropZ', cropZVal, ...
    'GTMeshSpacing', gtMeshSpacingVal, 'MaxEvalPoints', maxEvalPointsVal, ...
    'ChunkSizeNN', chunkSizeNNVal, 'ChunkSizeMesh', chunkSizeMeshVal, ...
    'TriangleCandidates', triangleCandidatesVal, ...
    'MakeFigure', false, 'Verbose', false);

write_case_txt(fullfile(pairA_outDir, sprintf('%s_summary.txt', pairA_label)), ...
    pairA_label, [45 225], elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, metricsPairA);

results = [results; make_row( ...
    pairA_label, "two_view_merge", "45,225", 2, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
    metricsPairA.mesh_surface_one_sided_rmse, ...
    metricsPairA.centroid_symmetric_rmse, ...
    metricsPairA.covered_gt_area_fraction_005, ...
    metricsPairA.covered_gt_area_fraction_010, ...
    metricsPairA.covered_gt_area_fraction_020, ...
    metricsPairA.cropped_point_count, ...
    "ok", "", string(pairA_outDir))];

% Pair B: 135 + 315
pairB_label = sprintf('pair_135_315_el%02d_b%03d', round(elevationDeg), round(1000*baselineVal));
pairB_outDir = fullfile(studyRoot, pairB_label); if ~exist(pairB_outDir, 'dir'), mkdir(pairB_outDir); end
reconPairB = merge_reconstructed_clouds(reconCell{2}, reconCell{4}, ...
    'VoxelSize', mergeVoxelSizeVal, 'MakeFigure', false, 'Verbose', false);
statsPairB = analyze_pointcloud(reconPairB, ...
    'CropX', cropXVal, 'CropY', cropYVal, 'CropZ', cropZVal, ...
    'MakeFigure', false, 'Verbose', false);
metricsPairB = compute_gt_metrics_jason_ship(reconPairB, ...
    'CropX', cropXVal, 'CropY', cropYVal, 'CropZ', cropZVal, ...
    'GTMeshSpacing', gtMeshSpacingVal, 'MaxEvalPoints', maxEvalPointsVal, ...
    'ChunkSizeNN', chunkSizeNNVal, 'ChunkSizeMesh', chunkSizeMeshVal, ...
    'TriangleCandidates', triangleCandidatesVal, ...
    'MakeFigure', false, 'Verbose', false);

write_case_txt(fullfile(pairB_outDir, sprintf('%s_summary.txt', pairB_label)), ...
    pairB_label, [135 315], elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, metricsPairB);

results = [results; make_row( ...
    pairB_label, "two_view_merge", "135,315", 2, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
    metricsPairB.mesh_surface_one_sided_rmse, ...
    metricsPairB.centroid_symmetric_rmse, ...
    metricsPairB.covered_gt_area_fraction_005, ...
    metricsPairB.covered_gt_area_fraction_010, ...
    metricsPairB.covered_gt_area_fraction_020, ...
    metricsPairB.cropped_point_count, ...
    "ok", "", string(pairB_outDir))];

%% ------------------------------------------------------------
% MERGE ALL FOUR
% -------------------------------------------------------------
fourViewLabel = sprintf('four_view_merged_el%02d_b%03d', round(elevationDeg), round(1000*baselineVal));
fourViewOutDir = fullfile(studyRoot, fourViewLabel); if ~exist(fourViewOutDir, 'dir'), mkdir(fourViewOutDir); end

reconFour = merge_reconstructed_clouds(reconPairA, reconPairB, ...
    'VoxelSize', mergeVoxelSizeVal, 'MakeFigure', false, 'Verbose', false);

statsFour = analyze_pointcloud(reconFour, ...
    'CropX', cropXVal, 'CropY', cropYVal, 'CropZ', cropZVal, ...
    'MakeFigure', false, 'Verbose', false);

metricsFour = compute_gt_metrics_jason_ship(reconFour, ...
    'CropX', cropXVal, 'CropY', cropYVal, 'CropZ', cropZVal, ...
    'GTMeshSpacing', gtMeshSpacingVal, 'MaxEvalPoints', maxEvalPointsVal, ...
    'ChunkSizeNN', chunkSizeNNVal, 'ChunkSizeMesh', chunkSizeMeshVal, ...
    'TriangleCandidates', triangleCandidatesVal, ...
    'MakeFigure', false, 'Verbose', false);

write_case_txt(fullfile(fourViewOutDir, sprintf('%s_summary.txt', fourViewLabel)), ...
    fourViewLabel, viewAzList, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, metricsFour);

results = [results; make_row( ...
    fourViewLabel, "four_view_merge", "45,135,225,315", 4, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
    metricsFour.mesh_surface_one_sided_rmse, ...
    metricsFour.centroid_symmetric_rmse, ...
    metricsFour.covered_gt_area_fraction_005, ...
    metricsFour.covered_gt_area_fraction_010, ...
    metricsFour.covered_gt_area_fraction_020, ...
    metricsFour.cropped_point_count, ...
    "ok", "", string(fourViewOutDir))];

%% ------------------------------------------------------------
% SAVE SUMMARY
% -------------------------------------------------------------
summaryCsv = fullfile(metricsDir, 'four_view_capstone_summary.csv');
summaryMat = fullfile(metricsDir, 'four_view_capstone_summary.mat');

writetable(results, summaryCsv);
save(summaryMat, 'results', 'metricsFour', 'metricsPairA', 'metricsPairB');

fprintf('\n============================================================\n');
fprintf('FOUR-VIEW CAPSTONE COMPLETE\n');
fprintf('Summary CSV:\n%s\n', summaryCsv);
fprintf('Summary MAT:\n%s\n', summaryMat);
fprintf('============================================================\n');

disp(results(:, {'CaseLabel','CaseType','Azimuths','NumViews', ...
    'MergedMeshRMSE_m','MergedSymCentroidRMSE_m', ...
    'MergedGTAreaFrac_005m','MergedGTAreaFrac_010m','MergedGTAreaFrac_020m'}));

%% ============================================================
% LOCAL FUNCTIONS
% ============================================================
function [reconOut, statsOut, metricsOut] = run_single_view_reconstruction( ...
    azimuthDeg, elevationDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
    disparityRangeVal, maxDepthVal, minValidDispVal, backgroundThresholdVal, ...
    cropXVal, cropYVal, cropZVal, ...
    gtMeshSpacingVal, maxEvalPointsVal, chunkSizeNNVal, chunkSizeMeshVal, triangleCandidatesVal)

    [renderData, rig, sceneInfo] = render_jason_ship_stereo( ...
        'ShipScript', 'oil_tanker_generate_Tanker.m', ...
        'AzimuthDeg', azimuthDeg, ...
        'ElevationDeg', elevationDeg, ...
        'Range', rangeVal, ...
        'Baseline', baselineVal, ...
        'ImageSize', imageSizeVal, ...
        'HFOVDeg', hfovDegVal, ...
        'MakeFigure', false, ...
        'Verbose', false, ...
        'SaveImages', false);

    reconOut = reconstruct_pointcloud(renderData, rig, ...
        'DisparityRange', disparityRangeVal, ...
        'MakeFigure', false, ...
        'Verbose', false, ...
        'SavePointCloud', false, ...
        'MaxDepth', maxDepthVal, ...
        'UseAdaptiveHistEq', true, ...
        'MinValidDisparity', minValidDispVal, ...
        'BackgroundThreshold', backgroundThresholdVal);

    statsOut = analyze_pointcloud(reconOut, ...
        'CropX', cropXVal, ...
        'CropY', cropYVal, ...
        'CropZ', cropZVal, ...
        'MakeFigure', false, ...
        'Verbose', false);

    metricsOut = compute_gt_metrics_jason_ship(reconOut, ...
        'CropX', cropXVal, ...
        'CropY', cropYVal, ...
        'CropZ', cropZVal, ...
        'GTMeshSpacing', gtMeshSpacingVal, ...
        'MaxEvalPoints', maxEvalPointsVal, ...
        'ChunkSizeNN', chunkSizeNNVal, ...
        'ChunkSizeMesh', chunkSizeMeshVal, ...
        'TriangleCandidates', triangleCandidatesVal, ...
        'MakeFigure', false, ...
        'Verbose', false);
end

function row = make_row(caseLabel, caseType, azimuths, numViews, elevDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, ...
    meshRMSE, symCentRMSE, area005, area010, area020, croppedPts, status, notes, outDir)

    row = table( ...
        string(caseLabel), ...
        string(caseType), ...
        string(azimuths), ...
        numViews, ...
        elevDeg, ...
        baselineVal, ...
        rangeVal, ...
        hfovDegVal, ...
        imageSizeVal(1), ...
        imageSizeVal(2), ...
        meshRMSE, ...
        symCentRMSE, ...
        area005, ...
        area010, ...
        area020, ...
        croppedPts, ...
        string(status), ...
        string(notes), ...
        string(outDir), ...
        'VariableNames', { ...
            'CaseLabel', ...
            'CaseType', ...
            'Azimuths', ...
            'NumViews', ...
            'Elevation_deg', ...
            'Baseline', ...
            'Range', ...
            'HFOV_deg', ...
            'ImageH', ...
            'ImageW', ...
            'MergedMeshRMSE_m', ...
            'MergedSymCentroidRMSE_m', ...
            'MergedGTAreaFrac_005m', ...
            'MergedGTAreaFrac_010m', ...
            'MergedGTAreaFrac_020m', ...
            'CroppedPointCount', ...
            'Status', ...
            'Notes', ...
            'OutputDir' ...
        });
end

function write_case_txt(txtPath, caseLabel, azimuths, elevDeg, baselineVal, rangeVal, hfovDegVal, imageSizeVal, metrics)
    fid = fopen(txtPath, 'w');
    if fid == -1
        return;
    end
    fprintf(fid, 'CaseLabel: %s\n', caseLabel);
    fprintf(fid, 'Azimuths: %s\n', mat2str(azimuths));
    fprintf(fid, 'Elevation_deg: %.6f\n', elevDeg);
    fprintf(fid, 'Baseline: %.6f\n', baselineVal);
    fprintf(fid, 'Range: %.6f\n', rangeVal);
    fprintf(fid, 'HFOV_deg: %.6f\n', hfovDegVal);
    fprintf(fid, 'ImageSize: [%d %d]\n', imageSizeVal(1), imageSizeVal(2));
    fprintf(fid, '\n');
    fprintf(fid, 'Merged mesh RMSE (m): %.12f\n', metrics.mesh_surface_one_sided_rmse);
    fprintf(fid, 'Merged sym centroid RMSE (m): %.12f\n', metrics.centroid_symmetric_rmse);
    fprintf(fid, 'Merged GT area frac @ 0.05 m: %.12f\n', metrics.covered_gt_area_fraction_005);
    fprintf(fid, 'Merged GT area frac @ 0.10 m: %.12f\n', metrics.covered_gt_area_fraction_010);
    fprintf(fid, 'Merged GT area frac @ 0.20 m: %.12f\n', metrics.covered_gt_area_fraction_020);
    fprintf(fid, 'Merged cropped point count: %.0f\n', metrics.cropped_point_count);
    fclose(fid);
end